resources:
  - name: gitResource
    type: GitRepo
    configuration:
      gitProvider: gitResource
      path: ChaitanyaVootla/ymlTest
pipelines: 
  - name: columnBug
    steps:
      - name: step1
        type: Bash
        configuration:
          inputResources:
            - name: gitResource
        execution:
          onExecute:
            - echo 'done'
      - name: step2
        type: Bash
        configuration:
          inputResources:
            - name: gitResource
          inputSteps:
            - name: step1
        execution:
          onExecute:
            - echo 'done'
      - name: step3
        type: Bash
        configuration:
          inputResources:
            - name: gitResource
          inputSteps:
            - name: step2
        execution:
          onExecute:
            - echo 'done'
      - name: step4
        type: Bash
        configuration:
          inputResources:
            - name: gitResource
          inputSteps:
            - name: step3
        execution:
          onExecute:
            - echo 'done'
      - name: step5
        type: Bash
        configuration:
          inputResources:
            - name: gitResource
          inputSteps:
            - name: step4
        execution:
          onExecute:
            - echo 'done'
      - name: step6
        type: Bash
        configuration:
          inputResources:
            - name: gitResource
          inputSteps:
            - name: step5
        execution:
          onExecute:
            - echo 'done'
      - name: step7
        type: Bash
        configuration:
          inputResources:
            - name: gitResource
          inputSteps:
            - name: step6
        execution:
          onExecute:
            - echo 'done'
      - name: step8
        type: Bash
        configuration:
          inputResources:
            - name: gitResource
          inputSteps:
            - name: step7
        execution:
          onExecute:
            - echo 'done'
      - name: distribution
        type: Bash
        configuration:
          inputResources:
            - name: gitResource
          inputSteps:
            - name: step3
            - name: jfrog_xray_java_client
        execution:
          onExecute:
            - echo 'done'
      - name: jfrog_xray_java_client
        type: Bash
        configuration:
          inputResources:
            - name: gitResource
          inputSteps:
            - name: step1
        execution:
          onExecute:
            - echo 'done'
  - name: state_test
    steps:
      - name: testReport_u18
        type: Bash
        configuration:
          inputResources:
            - name: gitResource
        execution:
          onExecute:
            - pushd $res_gitResource_resourcePath
            - sudo chmod +x echoTest.sh
            - ./echoTest.sh
      
      - name: run_file_restore
        type: Bash
        configuration:
          inputSteps:
            - name: testReport_u18
        execution:
          onExecute:
            - printenv
  - name: trigger_test
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          priority: 0
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_2
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_1
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_3
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_2
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: publish_chart_helm_test_test
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_3
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_5
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_1
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_6
        type: Bash
        configuration:
          inputSteps:
            - name: publish_chart_helm_test_test
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_7
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_5
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_8
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_1
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_9
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_1
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_10
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_1
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_11
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_7
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_12
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_9
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_test_
        type: Bash
        configuration:
          inputSteps:
            - name: publish_chart_helm_test_test
            - name: trigger_11
        execution:
          onExecute:
            - sleep 60
            - echo "done"
